### PR TITLE
remove imports without specifiers

### LINKED ISSUE #68: remove `import '@glimmer/env';`
Like https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/pull/38 and https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/pull/39, `import '@glimmer/env';` suffers the same problem and should be removed. It should also be fixed on the 0.1.x series.

### PR DESCRIPTION
**Pull request by kellyselden**
Closes #68. I branched off the latest stable tag. Can you push a 0.1.x branch so I can target that instead?

### CODE REVIEW

**Comment by rwjblue** [comment]
Does the issue not affect the master branch?

**Comment by kellyselden** [comment]
Probably, but the only version that showed up in my dependency tree was the 0.1.x series. I don't know the state of the betas, so it makes sense to fix it in stable to me.

**Comment by chadhietala** [comment]
I'm trying to understand what is going on here. Does this mean you can't use imports that have side effects? If so then unclear how things like this would work. https://github.com/glimmerjs/glimmer-vm/blob/master/packages/%40glimmer/runtime/lib/bootstrap.ts

**Comment by kellyselden** [comment]
No, it just means this plugin is not doing a complete job of stripping out these debug shim modules.

**Comment by chadhietala** [comment]
Ah seems good. Any possibility you can rebase?

**Comment by kellyselden** [comment]
> I branched off the latest stable tag. Can you push a 0.1.x branch so I can target that instead?

Rebasing to master wouldn't really be what I want, because everyone is using the 0.1.x release.

**Comment by rwjblue** [comment]
We should fix in master then backport as needed. There is no fundamental reason that we can't update ember-cli-babel to use the latest (current beta) version.  Just hasn't been done yet...

**Comment by kellyselden** [comment]
Here is the fix applied to master first.

**Pull request merged**
